
-------- CREATES THE TABLES FOR TRMS PROJECT---------------------------

--STEPS TO CREATE YOUR DABATASE:
1. RUN PART 1 TO CREATE ALL TABLES and sequences 
2. RUN PART II TO SEED VALUES INTO REFERENCE TABLES 

--******************************* PART I ******************************

CREATE TABLE "MEDALISTRELLES"."EVENT" 
   (	"EVENT_ID" NUMBER NOT NULL ENABLE, 
	"TIME" DATE NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"COST" NUMBER NOT NULL ENABLE, 
	"JUSTIFICATION" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"ATTACHMENT" NUMBER, 
	"GRADE" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"USER_ID_FK" NUMBER NOT NULL ENABLE, 
	"EVENT_STATUS_LT" NUMBER, 
	 CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_USERS_TABLE" FOREIGN KEY ("USER_ID_FK")
	  REFERENCES "MEDALISTRELLES"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


CREATE TABLE "MEDALISTRELLES"."EVENT_STATUS" 
   (	"EVENT_STATUS_ID" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EVENT_STATUS_PK" PRIMARY KEY ("EVENT_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


CREATE TABLE "MEDALISTRELLES"."EVENT_TYPE" 
   (	"EVENT_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EVENT_TYPE_PK" PRIMARY KEY ("EVENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

 CREATE TABLE "MEDALISTRELLES"."GRADING_FORMAT" 
   (	"GRADEFORMAT_ID" NUMBER NOT NULL ENABLE, 
	"FORMAT_NAME" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GRADING_FORMAT_PK" PRIMARY KEY ("GRADEFORMAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE TABLE "MEDALISTRELLES"."USER_ROLES" 
   (	"ROLE_ID" NUMBER NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USERROLES_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


  CREATE TABLE "MEDALISTRELLES"."USERS" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"USERROLE" NUMBER(2,0) NOT NULL ENABLE, 
	"HIREDATE" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"TUITION_BALANCE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "USERS_FK1" FOREIGN KEY ("USERROLE")
	  REFERENCES "MEDALISTRELLES"."USER_ROLES" ("ROLE_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


   
--PKs Sequences to auto-increment   
--1) EVENT_ID AUTO INCREMENT 
CREATE SEQUENCE PK_EVENTID START WITH 1 INCREMENT BY 1;
--2) EVENT_STATUS_ID INCREMENT 
CREATE SEQUENCE PK_EVENT_STATUS_ID START WITH 1 INCREMENT BY 1;
--3) EVENT_TYPEID INCREMENT
CREATE SEQUENCE PK_EVENT_TYPEID START WITH 1 INCREMENT BY 1;
--4) GRADEFORMAT_ID INCREMENT
CREATE SEQUENCE PK_GRADEFORMAT_ID START WITH 1 INCREMENT BY 1;
--5) ROLE_ID INCREMENT 
CREATE SEQUENCE PK_EVENTID START WITH 1 INCREMENT BY 1;
--6) USER_ID INCREMENT
CREATE SEQUENCE PK_USER_ID START WITH 1 INCREMENT BY 1;
--******************************* PART II ******************************  
INSERT INTO event_status  

--INSERT INTO suppliers
--(supplier_id, supplier_name)
--VALUES
--(5000, 'Apple');  
  
COMMIT;  

------------------  WORK LEFT TO BE DONE BY MEDALIS----------------------------  
--  2. Add information to the Part II
--  3. Auto-increment Pks
--  4.Add values to Event_status lookup table

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  