
  CREATE TABLE "WZHONG21"."USERS" 
   (	"USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HIREDDATE" DATE NOT NULL ENABLE, 
	"AVAILABLEREIMBURSEMENT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX (CREATE UNIQUE INDEX "WZHONG21"."USERS_PK1" ON "WZHONG21"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "WZHONG21"."TUITIONREIMBURSEMENTFORM" 
   (	"FORMID" NUMBER(*,0) NOT NULL ENABLE, 
	"EVENTDATE" DATE NOT NULL ENABLE, 
	"EVENTTIME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"COST" NUMBER NOT NULL ENABLE, 
	"GRADINGFORMAT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EVENTTYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"JUSTIFICATION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"GRADE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TUITIONREIMBURSEMENTFORM_PK" PRIMARY KEY ("FORMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TUITIONREIMBURSEMENTFORM_FK1" FOREIGN KEY ("USERNAME")
	  REFERENCES "WZHONG21"."USERS" ("USERNAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


   CREATE SEQUENCE  "WZHONG21"."FORMIDSEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 48 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;
